### ISSUE TITLE
Recommendations on input BAM file

### ISSUE THREAD

**Issue by kmavrommatis** [ohlerlab/RiboseQC#3]
Following up on #2 
are there any recommendation for duplicate reads if UMIs are not available? 
Should the duplicate reads be marked or removed?

Other than processing efficiency, is there any other benefit in removing rRNA and mtRNA from the file before processing with RiboseQC? 

Thanks in advance for your help

**Comment by ohlerlab** [comment]
Hey!
I don't have any recommendation for duplicate reads in the abscence of UMIs, no.

I imagine in this case that the CG content of the reads your looking at is going to play a large role, with more PCR bias (thus more duplicates) present in high CG content reads. I would probably produce some plots analyzing this, and maybe look into correcting your gene counts for GC content (you can do this for instance with gene-specific normalisation factors in DESeq2). You probably shouldn't just remove reads just because they have the same sequence - Riboseq reads do in fact pile up at specific locations for reasons other than PCR bias.

As for removed rRNA and mtRNA - yes there is a reason for this. These genes (especially rRNA) often have extremely high counts. Regions of the coding genome that happen to resemble rRNA can end up with large numbers of reads mismapping to them, so it's important to remove your contaminants before mapping Riboseq.

Note that this is also going to depress the number of reads you can map for such genes. This is fine if you are just comparing across conditions, but if comparing different genes, needs to be accounted for (as does mappability generally - a gene may look like it has few counts because only half of it is capable of emitting uniquely mappable Ribosomal footprints).
